[debug]
secret_key       = "qqrqdOg7fX4YNaDFzXf1mu6050BQ9okssS5sKkZFMVsd"
base_url         = "http://localhost:8001"
port             = 8001
email            = "Sendgrid | Folder"
sendgrid_api_key = "replace me"
email_folder     = "/path/to/email_folder"
admins           = ["admin@meet-os.com"]
from_email       = "no-reply@meet-os.com"
from_name        = "Meet-OS"

database_username  = "root"
database_password  = "root"
database_namespace = "meet-os-local-ns"
database_name      = "meet-os-local-db"


# We have this section to be able to try the --release flag during development
[release]
secret_key = "zqrqdOg7fX4YNaDFzXf1mu6050BQ9okssS5sKkZFMVsd"
base_url = "http://localhost:8001"
log_level = "normal"

